add: ワークフロー調整

diff --git a/.github/workflows/send-ssm-command.yml b/.github/workflows/send-ssm-command.yml
--- a/.github/workflows/send-ssm-command.yml
+++ b/.github/workflows/send-ssm-command.yml
@@ -71,8 +71,17 @@ jobs:
       - name: Fetch Command Output
         run: |
           echo "Command execution completed. Fetching output..."
-          aws ssm get-command-invocation \
+          COMMAND_INVOCATION=$(aws ssm get-command-invocation \
             --command-id ${{ env.COMMAND_ID }} \
             --instance-id "${{ env.INSTANCE_ID }}" \
             --query "{StandardOutputContent:StandardOutputContent, StandardErrorContent:StandardErrorContent, Status:Status}" \
-            --output json
+            --output json) | jq --raw-output \
+          'echo "Full invocation JSON: \(.)" >&2;
+          if .Status == "Failed" then
+              ("::error::SSM Command Status is Failed. Details: \(.)" | stderr),
+              halt_error(1)
+          else
+            .Status
+          end'
+
+          echo "SSM Command Status was not Failed."
